// TODO(solid-2): Review semantic migration sites in this file: createComputed, createEffect, createResource, on, splitProps.

// TODO(solid-2): Removed Solid 1 imports below are compatibility stubs for type-checking only. Replace each with a Solid 2 migration before relying on runtime behavior.
import { createEffect as __solid2CreateResourceEffect, createSignal as __solid2CreateResourceSignal } from "solid-js";
import { isServer as __solid2CreateResourceIsServer } from "@solidjs/web";
const createResource: { (source: any, fetcher: (value: any, info: any) => any, options?: any): any; (fetcher: (...args: any[]) => any, options?: any): any } = ((source: any, fetcher?: any, options?: any) => { const hasSource = typeof fetcher === "function"; const actualSource = hasSource ? source : undefined; const actualFetcher = hasSource ? fetcher : source; const actualOptions = hasSource ? options : fetcher ?? options; let latest = actualOptions?.initialValue; const [readLatest, setLatest] = __solid2CreateResourceSignal(latest as any, { ownedWrite: true }); const [readError, setError] = __solid2CreateResourceSignal<any>(undefined, { ownedWrite: true }); const [readLoading, setLoading] = __solid2CreateResourceSignal<boolean>(false, { ownedWrite: true }); const resource: any = () => { const error = readError(); if (error) throw error; return readLatest(); }; Object.defineProperty(resource, "latest", { get: () => readLatest() }); Object.defineProperty(resource, "error", { get: () => readError() }); Object.defineProperty(resource, "loading", { get: () => readLoading() }); Object.defineProperty(resource, "state", { get: () => readError() ? "errored" : readLoading() ? "pending" : readLatest() === undefined ? "unresolved" : "ready" }); const mutate = (value: any) => { setError(undefined as any); const next = typeof value === "function" ? value(latest) : value; latest = next; setLatest(() => next); return next; }; const fail = (err: any) => { setError(() => err); return undefined; }; const readSource = () => typeof actualSource === "function" ? actualSource() : actualSource; let requestId = 0; const run = (input: any, refetching?: any) => { if (hasSource && input === undefined) { setLoading(false); return Promise.resolve(undefined); } setLoading(true); const id = ++requestId; return Promise.resolve(typeof actualFetcher === "function" ? actualFetcher(input, { value: latest, refetching }) : input).then(value => { if (id === requestId) { setLoading(false); return mutate(value); } return value; }, err => { if (id === requestId) { setLoading(false); return fail(err); } return undefined; }); }; const refetch = function(value?: any) { const input = hasSource ? readSource() : arguments.length > 0 ? value : undefined; const refetching = arguments.length > 0 ? value : undefined; return run(input, refetching); }; if (!__solid2CreateResourceIsServer && hasSource) { let previousInput = readSource(); if (previousInput !== undefined) void run(previousInput); __solid2CreateResourceEffect(() => readSource(), (input: any) => { if (input === previousInput) return; previousInput = input; void run(input); }); } else if (!__solid2CreateResourceIsServer) void refetch(); return [resource, { mutate, refetch }]; }) as any;
import { createEffect as __solid2CreateEffect } from "solid-js";
import { isServer as __solid2IsServer } from "@solidjs/web";
const createEffect: (fn: (previous?: any) => any, value?: any, options?: any) => any = ((fn: (previous?: any) => any, value?: any, options?: any) => { if (__solid2IsServer) return undefined as any; let previous = value; return __solid2CreateEffect(() => fn(previous), (next: any) => { previous = next; }, options); }) as any;
const on: (deps: any, fn: (input: any, previousInput: any, previous?: any) => any, options?: any) => any = ((deps: any, fn: (input: any, previousInput: any, previous?: any) => any) => (previous?: any) => { const input = typeof deps === "function" ? deps() : Array.isArray(deps) ? deps.map((dep: any) => typeof dep === "function" ? dep() : dep) : deps; return fn(input, undefined, previous); }) as any;
const createComputed: (fn: (previous?: any) => any, value?: any, options?: any) => any = ((fn: (previous?: any) => any, value?: any) => fn(value)) as any;
type __Solid2SplitKeys<T extends object> = readonly (keyof T)[];
type __Solid2SplitRest<T extends object, Keys extends keyof T> = Omit<T, Keys>;
const splitProps: {
  <T extends object, K1 extends __Solid2SplitKeys<T>>(props: T, k1: K1): [Pick<T, K1[number]>, __Solid2SplitRest<T, K1[number]>];
  <T extends object, K1 extends __Solid2SplitKeys<T>, K2 extends __Solid2SplitKeys<T>>(props: T, k1: K1, k2: K2): [Pick<T, K1[number]>, Pick<T, K2[number]>, __Solid2SplitRest<T, K1[number] | K2[number]>];
  <T extends object, K1 extends __Solid2SplitKeys<T>, K2 extends __Solid2SplitKeys<T>, K3 extends __Solid2SplitKeys<T>>(props: T, k1: K1, k2: K2, k3: K3): [Pick<T, K1[number]>, Pick<T, K2[number]>, Pick<T, K3[number]>, __Solid2SplitRest<T, K1[number] | K2[number] | K3[number]>];
  <T extends object, K1 extends __Solid2SplitKeys<T>, K2 extends __Solid2SplitKeys<T>, K3 extends __Solid2SplitKeys<T>, K4 extends __Solid2SplitKeys<T>>(props: T, k1: K1, k2: K2, k3: K3, k4: K4): [Pick<T, K1[number]>, Pick<T, K2[number]>, Pick<T, K3[number]>, Pick<T, K4[number]>, __Solid2SplitRest<T, K1[number] | K2[number] | K3[number] | K4[number]>];
  <T extends object, K1 extends __Solid2SplitKeys<T>, K2 extends __Solid2SplitKeys<T>, K3 extends __Solid2SplitKeys<T>, K4 extends __Solid2SplitKeys<T>, K5 extends __Solid2SplitKeys<T>>(props: T, k1: K1, k2: K2, k3: K3, k4: K4, k5: K5): [Pick<T, K1[number]>, Pick<T, K2[number]>, Pick<T, K3[number]>, Pick<T, K4[number]>, Pick<T, K5[number]>, __Solid2SplitRest<T, K1[number] | K2[number] | K3[number] | K4[number] | K5[number]>];
} = ((props: any, ...keyGroups: any[]) => { const picked = new Set<any>(); const groups = keyGroups.map((group: any) => { const out: any = {}; for (const key of group ?? []) { picked.add(key); Object.defineProperty(out, key, { enumerable: true, configurable: true, get: () => props[key] }); } return out; }); const rest = new Proxy({}, { get: (_target, key: any) => picked.has(key) ? undefined : props[key], has: (_target, key: any) => !picked.has(key) && key in props, ownKeys: () => Reflect.ownKeys(props).filter((key: any) => !picked.has(key)), getOwnPropertyDescriptor: (_target, key: any) => picked.has(key) || !(key in props) ? undefined : { enumerable: true, configurable: true } }); return [...groups, rest]; }) as any;


// TODO(solid-2): Review createResource resource cluster.
const [user] = createResource(id, fetchUser);
// TODO(solid-2): Review createEffect split.
createEffect(on(user, value => console.log(value)));
// TODO(solid-2): Review createComputed write-back pattern.
createComputed(() => setValue(user()));
// TODO(solid-2): Review splitProps selected-prop usage; only rest-only cases are mechanically safe.
const [local, rest] = splitProps(props, ["class"]);
