export const importSourceReplacements = new Map<string, string>([
  ["solid-js/web", "@solidjs/web"],
  ["solid-js/h", "@solidjs/h"],
  ["solid-js/html", "@solidjs/html"],
  ["solid-js/universal", "@solidjs/universal"],
  ["solid-js/store", "solid-js"],
  ["solid-js/jsx-runtime", "@solidjs/web/jsx-runtime"],
  ["solid-js/jsx-dev-runtime", "@solidjs/web/jsx-dev-runtime"],
]);

export const safeImportRenames = new Map<string, string>([
  ["batch", "flush"],
  ["Suspense", "Loading"],
  ["SuspenseList", "Reveal"],
  ["ErrorBoundary", "Errored"],
  ["Index", "For"],
  ["mergeProps", "merge"],
  ["unwrap", "snapshot"],
  ["onMount", "onSettled"],
  ["equalFn", "isEqual"],
  ["getListener", "getObserver"],
]);

export const webSafeImportRenames = new Map<string, string>([["addEventListener", "addEvent"]]);

export const webReviewOnlyNames = new Set([
  "Aliases",
  "Properties",
  "classList",
  "clearDelegatedEvents",
  "effect",
  "getPropAlias",
  "setBoolAttribute",
  "ssrSpread",
  "SVGNamespace",
  "use",
]);

export const rendererTypeNames = new Set(["JSX", "ComponentProps"]);
export const solidTypeRenames = new Map<string, string>([["JSXElement", "Element"]]);
export const removedDomDirectivePrefixes = new Set(["oncapture"]);

export const reviewOnlyNames = new Set([
  "catchError",
  "$DEVCOMP",
  "$PROXY",
  "$TRACK",
  "cancelCallback",
  "createComputed",
  "createEffect",
  "createDeferred",
  "createDynamic",
  "createMemo",
  "createReaction",
  "createRoot",
  "createMutable",
  "createRenderEffect",
  "on",
  "createResource",
  "createSelector",
  "enableScheduling",
  "enableExternalSource",
  "from",
  "DEV",
  "EffectFunction",
  "InitializedResource",
  "InitializedResourceReturn",
  "MemoOptions",
  "OnEffectFunction",
  "OnOptions",
  "indexArray",
  "modifyMutable",
  "observable",
  "onError",
  "produce",
  "requestCallback",
  "resetErrorBoundaries",
  "ResolvedJSXElement",
  "Resource",
  "ResourceActions",
  "ResourceFetcher",
  "ResourceFetcherInfo",
  "ResourceOptions",
  "ResourceReturn",
  "ResourceSource",
  "ReconcileOptions",
  "splitProps",
  "startTransition",
  "Transition",
  "useTransition",
  "writeSignal",
]);
